### ISSUE TITLE
Cant run ffpb.py, Attribute Error

### ISSUE THREAD

**Issue by geekism** [althonos/ffpb#1]
This is the command i ran:

./ffpb.py -i family.guy.s16e08.720p.web.x264-tbs.mkv -s hd480 -c:v libx264 -crf 23 -c:a aac -strict -2 file.mkv

This is my error:

Traceback (most recent call last):
  File "./ffpb.py", line 41, in <module>
    class AbsoluteTimeETA(progressbar.AbsoluteETA):
AttributeError: 'module' object has no attribute 'AbsoluteETA'

AttributeError: 'module' object has no attribute 'AbsoluteETA'

**Comment by althonos** [comment]
You may have the wrong version of `progressbar` installed: try updating `progressbar2` like this:
```console
pip install -U --user progressbar2
```
