### ISSUE TITLE
Travis failing for missing mp3 file

### ISSUE THREAD

**Issue by expobrain** [althonos/ffpb#10]
Travis is failing because the website behind https://www.sample-videos.com/audio/mp3/wave.mp3 is gone.

Can it be replace with any other small mp3 file?

Is it worth it to commit the mp3 file in the repo to remove external dependencies?

**Comment by althonos** [comment]
Good catch, thanks. I'll find a small sample to add.

**Comment by althonos** [comment]
Fixed in ecfdea7e64f54ed84dd93e6948ea67e361727c5a.
