### ISSUE TITLE
Isnt transparent in a ffmpeg pipe 

### ISSUE THREAD

**Issue by gvonkreisler** [althonos/ffpb#16]
ffmpeg-bar -y -i  h:\3.mov -pix_fmt yuv422p -vcodec mpeg2video -non_linear_quant 1 -flags ^+ildct^+ilme -top 1 -dc 10 -intra_vlc 1 -r 25 -qmax 12 -lmin 1^*QP2LAMBDA -vtag xd5c -rc_max_vbv_use 1 -rc_min_vbv_use 1 -g 12 -b:v 50000k -minrate 50000k -maxrate 50000k -bufsize 8000k -acodec pcm_s16le -ar 48000 -bf 2 -ac 2 -f mxf - ^| bmxtranswrap.exe  -t avid --pstc --clip clip --project pro --import clip -o test -
ERROR
ERROR (libMXF): 'mxf_file_read(mxfFile, (uint8_t*)key, 16) == 16' failed, in ..\..\..\mxf\mxf_file.c:543
ERROR (libMXF): 'mxf_read_k(mxfFile, &tkey)' failed, in ..\..\..\mxf\mxf_partition.c:708
ERROR: Failed to find and read header partition
Warning: Open error 'MXF_RESULT_INVALID_FILE' near ..\..\..\src\mxf_reader\MXFFileReader.cpp:312
ERROR: Failed to open MXF file '': invalid or not an MXF file
Worked with ffmpeg
Chears

**Comment by althonos** [comment]
@gvonkreisler : this is not my package, check [`ffmpeg-bar`](https://github.com/sidneys/ffmpeg-progressbar-cli).
