### ISSUE TITLE
Run in Terminal Linux

### ISSUE THREAD

**Issue by kdantas** [althonos/ffpb#18]
Sorry to ask, but is it possible run ffpb with ffmpeg with Ubuntu 16.04 Xenial Xerus through Terminal Mode (SSH)? If so, can you explain how to install and run it? And really really sorry again, because I am very noob in Linux OS. Thanks in advance.

**Comment by althonos** [comment]
Yeah, you just need to install it on your remote machine (`pip install --user ffpb`) and then you can use it within you remote shell.

**Comment by kdantas** [comment]
Thanks. It´s running ok.
