### ISSUE TITLE
unable to install no module named 'fcntl' - window 10

### ISSUE THREAD

**Issue by Nex4rius** [althonos/ffpb#20]
<img src="https://imgur.com/IxlZ8nE.gif">

**Comment by althonos** [comment]
Hi @Nex4rius ,

`ffpb` relies on `sh`, which does not support Windows. Unfortunately, there is no workaround for now (see #11)

**Comment by Nex4rius** [comment]
Oh no this looked so promising :(

I think you should add something like this to it to avoid further confusion.
```python
if os.name == "nt":
    print("doesnt work on windows")
```

**Comment by althonos** [comment]
If you're on Win10, you can still use the [Linux subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10) :wink: 

It looks like until `sh` version `1.13`, it would print the following message at import error:
```python
ImportError: sh 1.13.1 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.
```

Seems like this was removed in latest `sh`, so I should add that message myself.

**Comment by varnav** [comment]
ModuleNotFoundError: No module named 'fcntl' - getting this with ffpb 0.3.0 on Windows

**Comment by Nex4rius** [comment]
It happens because ffpb uses the sh package which is not compatible with windows.
I did add windows support with https://github.com/althonos/ffpb/pull/21 but @althonos has not merged it into the stable branch and I don't have the permission to do it.


As a workaround you could just edit the file directly on your system and copy the <a href="https://github.com/althonos/ffpb/blob/cb7e6fb1e4be409a7a5914d2a4d2ba8b1aa1d5fb/ffpb.py">new version</a> into it. It should be somewhere like "C:\YOUR PYTHON DIRECTORY HERE\Lib\site-packages\ffpb\ffpb.py"

**Comment by althonos** [comment]
`v0.4.0` was just released, and `ffpb` now works on Windows thanks to @Nex4rius :tada:
