### ISSUE TITLE
Permission to embed your software into FFenmass.

### ISSUE THREAD

**Issue by ghost** [althonos/ffpb#28]
I'm having trouble using ffpb as an import as it does not properly invoke KeyboardException when triggered.

I am asking permission to modify your code from [ffpb.py](https://github.com/althonos/ffpb/blob/master/ffpb.py) and embed it into [FFenmass](https://github.com/NoPantsCrash/ffenmass).

Both FFenmass and ffpb are under MIT license, but I figured would be better to directly ask you.

**Comment by althonos** [comment]
Hi @NoPantsCrash ,

sure, you can embed it directly, but I guess maybe it's easier if I update the code to provide an intermediate function that does not capture exceptions. But note that `ffpb.main` always returns `130` when it gets interrupted (`128 + signal.SIGINT`), so you could also look for that and reraise a KeyboardInterrupt, e.g. in your code:

```python
#Checking if file doesn't already exists on the output directory
if not pathlib.Path(args[-1]).is_file():
    retcode = ffpb.main(args)
    if retcode == 130:
        raise KeyboardInterrupt()
```

**Comment by ghost** [comment]
@althonos Oh alright, sorry I did not notice that.
I'll add this on the next release, thank you.
