### ISSUE TITLE
Does it do correct conversions HH::MM:SS to seconds? 

### ISSUE THREAD

**Issue by beotiger** [althonos/ffpb#35]
Hi.
Module **ffpb/ffpb.py**, line **56**:
`        return (int(hours) * 60 + int(minutes)) * 60 + int(seconds)`

Should not it be:
`        return (int(hours) * 3600 + int(minutes)) * 60 + int(seconds)`

?
Hmmmm.

**Comment by althonos** [comment]
Brackets 😄

**Comment by beotiger** [comment]
> Brackets 😄

Uhhh, indeed, how could I misread it?
